language: cpp

os:
  - osx

osx_image: xcode9.4

addons:
  homebrew:
    packages:
    - sdl2_mixer
    - sdl2_ttf
    - libsodium

script:
	- xcodebuild -workspace "./Xcode/devilutionX.xcworkspace" -scheme "devilutionX" build
