language: bash

os:
  - osx

osx_image: xcode9.4

script:
    - bash ./xcode-build.sh --get-libs --build-libs --build-project --package

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "build/devilutionX.dmg"
  skip_cleanup: true
  on:
    tags: true
