language: cpp

os:
  - osx

osx_image: xcode9.4

addons:
  homebrew:
    packages:
    - sdl2_mixer
    - sdl2_ttf
    - libsodium

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(sysctl -n hw.physicalcpu)

xcode_workspace: ./Xcode/devilutionX.xcworkspace
xcode_scheme: devilutionX
xcode_destination: platform=macOS
